apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodedeploy
  name: nodedeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodedeploy
  template:
    metadata:
      labels:
        app: nodedeploy
    spec:
      containers:
      - image: 909484000752.dkr.ecr.us-east-1.amazonaws.com/node:latest
        name: node
